### ISSUE TITLE
isPage的判断太简单了

### ISSUE THREAD

**Issue by tourze** [LuckyHH/taro-inject-component-loader#2]
可以提供个选项给开发者自己去判断吧。例如我们的项目中，分包是通过模块名来定义的，那么就没办法用这个插件了

https://github.com/LuckyHH/taro-inject-component-loader/blob/09b23b2db69f0dc2c16872d6ca323e9c6e6717d5/src/index.ts#L36

**Comment by LuckyHH** [comment]
我没有看懂你这里说的“分包是通过模块名来定义的”是什么意思，你可以给一个简单的页面路径的例子吗？
Taro小程序中，页面文件定义还是比较灵活的，可以在页面文件夹中嵌套页面。
比如类似这样：
`/package-order/pages/order/index` 和 `/package-order/pages/order/create-order/index`
我们觉得这样不是很好的开发方式，因为嵌套着写，找页面还比较麻烦。

**Comment by tourze** [comment]
我们这里的情形是，为了跟h5那边兼容，以订单和商品为例，我们的路由名都类似下面这样：

/order/detail/index
/order/list/index
/goods/detail/index
/goods/search/index

各个小程序没特别限制路由必须包含某种关键词的（至少微信、头条都不限制），所以最好lib里面也不要直接根据关键词来判断js是否是页面

**Comment by LuckyHH** [comment]
@tourze 之前没有考虑过打包成其他平台的情形，那我把 isPage 判断作为可选配置开放给开发者吧。
